Repository changhui-chan/TeamSync, pull requests merged in 2025-02, with the labels that each got.

#12 fix: ESLint 설정 파일 에러 수정
  .eslintrc.json
  .husky/pre-commit
  .prettierrc
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/app/[teamid]/[taskid]/page.tsx
  src/app/[teamid]/tasklist/page.tsx
  src/app/addteam/page.tsx
  src/app/boards/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/myhistory/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  tailwind.config.ts
Labels: 🔧 Chore

#14 feat: 커밋 챌린지 인증 자동화 추가
  .github/workflows/main.yml
Labels: ✨ Feat

#16 feat: 워크플로우 수동 실행 기능 추가
  .github/workflows/main.yml
Labels: ✨ Feat

#19 chore: 커밋 인증 자동화 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#21 fix: 작업자 매핑 테이블 인덱스 접근 에러 수정
  .github/workflows/commit-notifier.yml
Labels: 🐛 Fix

#22 fix: 2차 커밋 인증 워크 플로우 에러 수정
  .github/workflows/commit-notifier.yml
Labels: 🐛 Fix

#24 fix: 3차 커밋 인증 워크 플로우 에러 수정
  .github/workflows/commit-notifier.yml
Labels: 🐛 Fix

#23 ✨ feat: tailwind 추가
  src/app/globals.css
  tailwind.config.ts
Labels: ✨ Feat

#26 fix: 5차 커밋 인증 워크 플로우 에러 수정
  .github/workflows/commit-notifier.yml
Labels: 🐛 Fix

#28 chore: 커밋 인증 워크 플로우 디테일 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#29 chore: 2차 커밋 인증 워크 플로우 디테일 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#36 chore: 2차 커밋 인증 워크 플로우 디테일 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#35 chore: ESLint 규칙 수정
  eslint.config.mjs
Labels: 🔧 Chore

#38 :wrench: chore: 커밋 저장 방식 및 웹 훅 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#31 feat: axios 인스턴스 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/lib/axiosInstance.ts
  src/util/toast.ts
Labels: ✨ Feat

#34 refactor: axios 인스턴스 리팩토링
  src/lib/axiosInstance.ts
Labels: ♻️ Refactor

#48 chore: 3차 커밋 인증 워크 플로우 디테일 수정
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#47 fix: ESLint 에러 수정
  eslint.config.mjs
  package-lock.json
  package.json
Labels: 🐛 Fix

#50 chore: 커밋 인증 워크 플로우 환경 변수 처리 변경
  .github/workflows/commit-notifier.yml
  webhook.env
Labels: 🔧 Chore

#51 chore: 커밋 인증 워크 플로우 환경 변수 처리 변경
  webhook.env
Labels: 🔧 Chore

#52 chore: 3차 커밋 인증 워크 플로우 환경 변수 처리 변경
  .gitignore
Labels: 🔧 Chore

#45 ✨feat: 공용 인풋 컴포넌트 구현
  src/shared/input.tsx
Labels: ✨ Feat

#62 feat: 헤더 1차 개발
  eslint.config.mjs
  src/shared/DeleteThisFile.txt
  src/shared/header/Header.tsx
Labels: ✨ Feat

#55 ♻️ refactor: props html Element 처리
  src/shared/input.tsx
Labels: ♻️ Refactor

#67 feat: 랜딩페이지 틀 짜기
  public/icon/DeleteThisFile.txt
  public/icon/ic-repair.svg
  src/feature/landing/DeleteThisFile.txt
  src/feature/landing/Home.tsx
Labels: ✨ Feat

#68 feat: 팀 페이지 틀 짜기
  src/feature/[teamid]/DeleteThisFile.txt
  src/feature/[teamid]/Team.tsx
Labels: ✨ Feat

#65 feat: 할일 리스트 페이지 2차 개발
  package-lock.json
  package.json
  src/app/[teamid]/tasklist/page.tsx
  src/feature/[teamid]/tasklist/TaskItem.tsx
  src/feature/[teamid]/tasklist/TaskListPage.tsx
  tailwind.config.ts
Labels: ✨ Feat, ♻️ Refactor

#85 chore: 커밋 인증 워크 플로우 롤백
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#86 chore: 2차 커밋 인증 워크 플로우 롤백
  .github/workflows/commit-notifier.yml
Labels: 🔧 Chore

#81 ✨feat: textarea 외부 label 추가 생성
  src/shared/textArea.tsx
Labels: ✨ Feat

#88 feat: 비밀번호 visible 컴포넌트 추가
  package.json
  src/shared/input/eyeButton.tsx
  src/shared/input/input.tsx
  src/shared/input/textArea.tsx
Labels: ✨ Feat

#74 feat: API 타입 정의 및 공통 함수 추가
  src/api/DeleteThisFile.txt
  src/api/index.ts
  src/api/type/DeleteThisFile.txt
  src/api/type/article.d.ts
  src/api/type/articleComment.d.ts
  src/api/type/auth.d.ts
  src/api/type/comment.d.ts
  src/api/type/group.d.ts
  src/api/type/image.d.ts
  src/api/type/index.ts
  src/api/type/oauth.d.ts
  src/api/type/recurring.d.ts
  src/api/type/shared.d.ts
  src/api/type/task.d.ts
  src/api/type/taskList.d.ts
  src/api/type/user.d.ts
  src/api/util/DeleteThisFile.txt
  src/api/util/apiService.ts
  src/api/util/createMutations.ts
  src/api/util/createQueries.ts
  src/api/util/defaultOptions.ts
  src/api/util/queryHelpers.ts
  src/app/layout.tsx
  src/app/queryProvider.tsx
  src/lib/DeleteThisFile.txt
  src/lib/axiosInstance.ts
  tsconfig.json
Labels: ✨ Feat, 🔧 Chore

#73 feat: window.inner usehook 구현
  package.json
  src/hook/useDevice.ts
Labels: ✨ Feat

#82 feat: 공통 모달 구현
  src/app/globals.css
  src/app/layout.tsx
  src/hook/useEscapeKey.ts
  src/hook/useReset.ts
  src/hook/useTrapFocus.ts
  src/shared/modal/Modal.tsx
  src/shared/modal/atom/modalAtom.ts
  src/shared/modal/hook/useModal.ts
  src/util/clickHandlers.ts
  tailwind.config.ts
Labels: ✨ Feat

#89 feat: 로그인 1차 개발
  src/app/login/page.tsx
  src/shared/input/errorMessage.tsx
  src/shared/input/eyeButton.tsx
  src/shared/input/input.tsx
Labels: ✨ Feat, 🔧 Chore

#92 fix: mutationFn 타입 오류 수정
  src/api/index.ts
  src/api/util/createMutations.ts
  src/api/util/createQueries.ts
  src/api/util/queryHelpers.ts
Labels: 🐛 Fix

#94 feat: 로그인 페이지 2차 개발
  src/app/login/page.tsx
  src/shared/input/input.tsx
Labels: ✨ Feat

#97 feat:유저 정보 저장
  src/app/login/page.tsx
  src/feature/login/DeleteThisFile.txt
  src/store/DeleteThisFile.txt
  src/store/userAtom.tsx
Labels: ✨ Feat

#98 feat: 헤더 2차 개발
  package-lock.json
  public/icon/ic-logo.svg
  src/app/layout.tsx
  src/shared/header/Header.tsx
  src/shared/header/components/Forum.tsx
  src/shared/header/components/Logo.tsx
  src/shared/header/components/Menu.tsx
  src/shared/header/components/Sidebar.tsx
  src/shared/header/components/TeamNav.tsx
  src/shared/header/components/TeamNavDropdown.tsx
  src/shared/header/components/UserProfile.tsx
  src/shared/header/components/UserProfileDropdown.tsx
Labels: ✨ Feat

#104 chore: 테일윈드 설정 수정
  src/app/globals.css
  tailwind.config.ts
Labels: 🔧 Chore

#100 feat: 모달 인스턴스화 구현
  src/app/globals.css
  src/hook/useEscapeKey.ts
  src/hook/useTrapFocus.ts
  src/shared/modal/Modal.tsx
  src/shared/modal/atom/modalAtom.ts
  src/shared/modal/hook/useModal.ts
Labels: ✨ Feat, ♻️ Refactor

#108 feat: 렌딩페이지 2차 개발
  public/icon/ic-done.svg
  public/icon/ic-folderFill.svg
  public/icon/ic-messageAltFill.svg
  public/image/DeleteThisFile.txt
  public/image/img-banner.svg
  public/image/img-bannerMobile.svg
  public/image/img-bannerTablet.svg
  public/image/img-footer.svg
  public/image/img-home1.svg
  public/image/img-home2.svg
  public/image/img-home3.svg
  src/feature/landing/Home.tsx
Labels: ✨ Feat

#116 fix: use client 추가
  src/hook/useDevice.ts
Labels: 🐛 Fix

#115 fix: 불필요한 DELETE 요청 발생 문제 수정
  src/api/index.ts
Labels: 🐛 Fix
